import urllib.parse

IOTSERVER = '192.168.1.121:3001'
CONTINUE_THREAD = True

CAMERA_IP = '192.168.100.230:554'
CAMERA_USERNAME = "admin"
CAMERA_PASSWORD = "energyCam#1"
ENCODED_USERNAME = urllib.parse.quote(CAMERA_USERNAME)
ENCODED_PASSWORD = urllib.parse.quote(CAMERA_PASSWORD)
RTSP_URL = f"rtsp://{ENCODED_USERNAME}:{ENCODED_PASSWORD}@{CAMERA_IP}"

CAMERA_ID = 1

IMAGE_PATH = 'camera_image.jpg'
